---
# roles/system_init/handlers/main.yml

- name: Source profile
  shell: source /etc/profile

- name: Restart sshd
  service:
    name: sshd
    state: restarted

- name: Exec network config
  shell: sh /tmp/network.sh

- name: Restart rsyslog service
  service:
    name: rsyslog
    state: restarted
    enabled: yes
