---
# roles/ironic/tasks/auth.yml

- block:
  - name: Create ironic user
    os_user:
      state: present
      name: ironic
      password: "{{ openstack_ironic.auth.password }}"
      domain: default
      default_project: service

  - name:  Add admin role to the user ironic
    os_user_role:
      user: ironic
      role: admin
      project: service

  - name: Create ironic service entity
    os_keystone_service:
      state: present
      name: ironic
      service_type: baremetal
      description: Ironic baremetal provisioning service

  - name: Create the image API endpoint
    os_keystone_endpoint:
      service: ironic
      endpoint_interface: "{{ item }}"
      url: http://{{ ironic_api_host }}:{{ ironic_api_port }}
      region: RegionOne
      state: present
    loop:
      - admin
      - public
      - internal
  environment:
    OS_PROJECT_DOMAIN_NAME: default
    OS_USER_DOMAIN_NAME: default
    OS_PROJECT_NAME: admin
    OS_USERNAME: admin
    OS_PASSWORD: "{{ openstack_keystone.auth.password }}"
    OS_AUTH_URL: "http://{{ auth_admin_host }}:{{ auth_admin_port }}/v3"
    OS_IDENTITY_API_VERSION: 3
    OS_IMAGE_API_VERSION: 2
