---
- name: Make sure neutron-l3-agent is stoppped and disabled
  service:
    name: neutron-l3-agent
    state: stopped
    enabled: false
  delegate_to: "{{ outer_item }}"
  ignore_errors: true
  tags:
    - ironic_config_neutron_compute

- name: Update openvswitch_agent_ini
  ini_file:
    path: /etc/neutron/plugins/ml2/openvswitch_agent.ini
    section: agent
    option: enable_distributed_routing
    value: 'False'
    owner: root
    group: neutron
    mode: 0640
  delegate_to: "{{ outer_item }}"
  tags:
    - ironic_config_neutron_compute
  notify:
    - Restart neutron-openvswitch-agent.service
