---
# roles/system_init/tasks/limits_config.yml

- name: Limits config
  pam_limits:
    dest: "{{ item.dest }}"
    domain: '*'
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  loop:
    - { dest: '/etc/security/limits.conf',limit_type: 'soft',limit_item: 'nofile',value: '655350' }
    - { dest: '/etc/security/limits.conf',limit_type: 'hard',limit_item: 'nofile',value: '655350' }
    - { dest: '/etc/security/limits.conf',limit_type: 'soft',limit_item: 'nproc',value: '102400' }
    - { dest: '/etc/security/limits.conf',limit_type: 'hard',limit_item: 'nproc',value: '102400' }
    - { dest: '/etc/security/limits.d/20-nproc.conf',limit_type: 'soft',limit_item: 'nproc',value: '102400' }
