---
- name: Make haproxy bindable on non local addresses
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: 1
    sysctl_set: yes
    state: present

- name: Make net.ipv4.ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present

- name: Add group haproxy
  group:
    name: haproxy
    state: present

- name: Add user haproxy
  user:
    name: haproxy
    group: haproxy
    home: /home/haproxy
    state: present
