---
- name: Config nova_novncproxy iptables
  iptables:
    action: insert
    chain: INPUT
    jump: ACCEPT
    source: '{{ network_openstack.management.cidr }}'
    protocol: tcp
    match: multiport
    destination_port: '{{ openstack_nova.port.novncproxy }}'

- name: Insert tcp rule to /etc/sysconfig/iptables
  blockinfile:
    path: /etc/sysconfig/iptables
    marker: '#{mark} iptables rules for OpenStack nova-novncproxy {mark}#'
    insertafter: '^:OUTPUT ACCEPT '
    block: |
      -A INPUT -s {{ network_openstack.management.cidr }} -p tcp -m multiport --dport {{ openstack_nova.port.novncproxy }} -j ACCEPT
