---
- name: Install cinder packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - openstack-cinder
    - python-crypto
    - python-oslo-db
    - python-oslo-log
    - MySQL-python
    - openstack-selinux

- name: Ceph packages install
  yum:
    name: ceph
    state: present
  when: "'ceph' in backend_openstack.cinder.backends"
