---
- name: Add rabbitmq user
  rabbitmq_user:
    user: '{{ rabbitmq_user }}'
    password: '{{ rabbitmq_pass }}'
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present
  run_once: true
