---
- name: Set rabbitmq limitnofile
  blockinfile:
    path: /usr/lib/systemd/system/rabbitmq-server.service
    insertafter: 'Group=rabbitmq'
    block: 'LimitNOFILE=10240'

- name: Create log directory
  file:
    path: "{{ rabbitmq_log_path }}"
    owner: rabbitmq
    group: rabbitmq
    state: directory
    recurse: yes

- name: Config rabbitmq
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'rabbitmq.config.j2', dest: '/etc/rabbitmq/rabbitmq.config' }
    - { src: 'rabbitmq-env.conf.j2', dest: '/etc/rabbitmq/rabbitmq-env.conf' }
  notify: Restart rabbitmq-server

- name: Be sure rabbitmq is running and enabled
  service:
    name: rabbitmq-server
    state: started
    enabled: true
