---
- name: Install rabbitmq packages
  yum:
    name: rabbitmq-server
    state: present

- name: Install rsync packages
  yum:
    name: rsync
    state: present
  when:
    - ansible_play_batch|length > 1
    - inventory_hostname == master
