---
- name: Config neutron ha iptables
  iptables:
    action: insert
    chain: INPUT
    jump: ACCEPT
    source: '{{ network_openstack.management.cidr }}'
    protocol: tcp
    match: multiport
    destination_port: '{{ openstack_neutron.port_ha }}'
  run_once: true
  delegate_to: "{{ outer_item }}"
  tags: neutron_controller_ha

- name: Insert tcp rule to /etc/sysconfig/iptables
  blockinfile:
    path: /etc/sysconfig/iptables
    marker: '#{mark} iptables for OpenStack Neutron ha {mark}#'
    insertafter: '^:OUTPUT ACCEPT '
    block: |
        -A INPUT -s {{ network_openstack.management.cidr }} -p tcp -m multiport --dport {{ openstack_neutron.port_ha }} -j ACCEPT
  run_once: true
  delegate_to: "{{ outer_item }}"
  tags: neutron_controller_ha

- name: Insert neutron into haproxy info /etc/haproxy/haproxy.cfg
  blockinfile:
    path: /etc/haproxy/haproxy.cfg
    marker: '#{mark} listen for OpenStack neutron-server {mark}#'
    state: present
    block: |
        listen neutron
          bind {{ neutron_server_host }}:{{ neutron_server_port }}
          balance roundrobin
          option  tcpka
          option  httpchk
          option  httplog
         {% for host in groups['neutron_server'] %}
         server node-{{ loop.index }} {{ host }}:{{ openstack_neutron.port }} check inter 2000 rise 2 fall 5
         {% endfor %}
  run_once: true
  notify: Restart haproxy
  delegate_to: "{{ outer_item }}"
  tags: neutron_controller_ha
