---
- import_tasks: iptables.yml
  tags: neutron_controller_iptables

- import_tasks: install.yml
  tags: neutron_controller_install

- import_tasks: db.yml
  tags: neutron_controller_db

- import_tasks: auth.yml
  tags: neutron_controller_auth

- import_tasks: config.yml
  tags: neutron_controller_config

- import_tasks: db_sync.yml
  tags: neutron_controller_db_sync

- import_tasks: start.yml
  tags: neutron_controller_start

- include_tasks: ha.yml
  tags: neutron_controller_ha
  loop: "{{ groups['os_ha'] }}"
  loop_control:
    loop_var: outer_item
  when: network_openstack.management.vip is defined and network_openstack.management.vip
