---
- name: Configure MySQL user (nova)
  include_tasks: "{{ playbook_dir }}/common-tasks/mysql_db_user.yml"
  vars:
    mysql_user_name: "{{ openstack_nova.db.user }}"
    mysql_user_password: "{{ openstack_nova.db.password }}"
    mysql_login_host: "{{ db_host }}"
    mysql_login_port: "{{ db_port }}"
    mysql_db_name: "{{ outer_item }}"
  run_once: true
  loop: "{{ openstack_nova.db.databases }}"
  loop_control:
    loop_var: outer_item
