---
- include_tasks: ha.yml
  loop: "{{ groups['os_ha'] }}"
  loop_control:
    loop_var: outer_item
  when: network_openstack.management.vip is defined and network_openstack.management.vip
  tags:
    - nova_controller_ha

- import_tasks: iptables.yml
  tags:
    - nova_controller_iptables

- import_tasks: install.yml
  tags:
    - nova_controller_install

- include_tasks: db.yml
  tags:
    - nova_controller_db

- import_tasks: auth.yml
  tags:
    - nova_controller_auth

- import_tasks: config.yml
  tags:
    - nova_controller_config

- import_tasks: db_sync.yml
  run_once: true
  tags:
    - nova_controller_db_sync

- import_tasks: start.yml
  tags:
    - nova_controller_start
