---
- name: Config /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item]['ansible_' + network_mariadb.internal.interface]['ipv4']['address'] }} {{ hostvars[item].ansible_hostname }}"
    state: present
  loop: '{{ ansible_play_hosts }}'
  when: ansible_play_batch|length > 1
  tags: mariadb_hostname
