---
- name: Make sure serivces are enabled and started
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - xinetd
    - openstack-ironic-inspector-dnsmasq
    - openstack-ironic-inspector
