---
- name: Configure MySQL user (cinder)
  include_tasks: "{{ playbook_dir }}/common-tasks/mysql_db_user.yml"
  vars:
    mysql_user_name: "{{ openstack_cinder.db.user }}"
    mysql_user_password: "{{ openstack_cinder.db.password }}"
    mysql_login_host: '{{db_host}}'
    mysql_login_port: "{{ db_port }}"
    mysql_db_name: "{{ openstack_cinder.db.database }}"
  run_once: true
