---
- name: Config cinder iptables
  iptables:
    action: insert
    chain: INPUT
    jump: ACCEPT
    source: '{{ network_openstack.management.cidr }}'
    protocol: tcp
    match: multiport
    destination_port: "{{ cinder_api_port }}"
  delegate_to: "{{ outer_item }}"
  tags: cinder_controller_ha

- name: Insert tcp rule to /etc/sysconfig/iptables
  blockinfile:
    path: /etc/sysconfig/iptables
    marker: '#{mark} iptables rules for cinder-api ha {mark}#'
    insertafter: '^:OUTPUT ACCEPT '
    block: |
      -A INPUT -s {{ network_openstack.management.cidr }} -p tcp -m multiport --dport {{ cinder_api_port }} -j ACCEPT
  delegate_to: "{{ outer_item }}"
  tags: cinder_controller_ha

- name: Insert cinder into haproxy info /etc/haproxy/haproxy.cfg
  blockinfile:
    path: /etc/haproxy/haproxy.cfg
    marker: '#{mark} listen for OpenStack cinder {mark}#'
    state: present
    block: |
        listen cinder-api
          bind {{ cinder_api_host }}:{{ cinder_api_port }}
          balance roundrobin
          option  tcpka
          option  httpchk
          option  httplog
         {% for host in groups['kgc_server'] %}
         server node-{{ loop.index }} {{ host }}:{{ openstack_cinder.port.api }} check inter 2000 rise 2 fall 5
         {% endfor %}
  run_once: true
  notify: Restart haproxy
  delegate_to: "{{ outer_item }}"
  tags: cinder_controller_ha
