---
# roles/keystone/tasks/config_single.yml

- name: Bootstrap the Identity service
  shell:
    cmd: |
      keystone-manage --config-dir /etc/keystone bootstrap --bootstrap-password {{ openstack_keystone.auth.password }} \
      --bootstrap-admin-url http://{{ auth_admin_host }}:{{ openstack_keystone.port.admin }}/v3/ \
      --bootstrap-internal-url http://{{ auth_public_host }}:{{ openstack_keystone.port.internal }}/v3/ \
      --bootstrap-public-url http://{{ auth_public_host }}:{{ openstack_keystone.port.public }}/v3/ \
      --bootstrap-region-id RegionOne

- name: Sync admin-openrc.sh
  template:
    src: admin-openrc.sh.j2
    dest: /root/admin-openrc.sh
    mode: 0755
  vars:
    controller_host: "{{ auth_admin_host }}"
    keystone_admin_port: "{{ openstack_keystone.port.admin }}"

- block:
  - name: Create service project
    os_project:
      name: service
      description: Service Project
      domain: default
      region_name: RegionOne
      enabled: true
      state: present
      wait: true

  - name: Create user role
    os_keystone_role:
      name: user
      state: present
      wait: true

  environment:
    OS_PROJECT_DOMAIN_NAME: default
    OS_USER_DOMAIN_NAME: default
    OS_PROJECT_NAME: admin
    OS_USERNAME: admin
    OS_PASSWORD: '{{ openstack_keystone.auth.password }}'
    OS_AUTH_URL: http://{{ auth_admin_host }}:{{ openstack_keystone.port.admin }}/v3
    OS_IDENTITY_API_VERSION: 3
    OS_IMAGE_API_VERSION: 2
