---
# roles/keystone/tasks/ha.yml

- name: Config keystone iptables
  iptables:
    action: insert
    chain: INPUT
    jump: ACCEPT
    source: '{{ network_openstack.management.cidr }}'
    protocol: tcp
    match: multiport
    destination_port: '{{ item }}'
  delegate_to: "{{ outer_item }}"
  loop:
    - '{{ openstack_keystone.port.admin_ha }}'
    - '{{ openstack_keystone.port.public_ha }}'
  tags:
    - keystone_ha

- name: Insert tcp rule to /etc/sysconfig/iptables
  blockinfile:
    path: /etc/sysconfig/iptables
    marker: '# {mark} iptables for keystone ha port {mark} #'
    insertafter: '^:OUTPUT ACCEPT '
    block: |
        -A INPUT -s {{ network_openstack.management.cidr }} -p tcp -m multiport --dport {{ openstack_keystone.port.admin_ha }} -j ACCEPT
        -A INPUT -s {{ network_openstack.management.cidr }} -p tcp -m multiport --dport {{ openstack_keystone.port.public_ha }} -j ACCEPT
  delegate_to: "{{ outer_item }}"
  tags:
    - keystone_ha

- name: Insert keystone into haproxy info /etc/haproxy/haproxy.cfg
  blockinfile:
    path: /etc/haproxy/haproxy.cfg
    marker: '# {mark} listen for OpenStack keystone {mark}'
    state: present
    block: |
        listen keystone-admin
          bind {{ auth_admin_host }}:{{ openstack_keystone.port.admin_ha }}
          balance roundrobin
          option  tcpka
          option  httpchk
          option  httplog
         {% for host in ansible_play_batch %}
         server node-{{ loop.index }} {{ host }}:{{ openstack_keystone.port.admin }} check inter 2000 rise 2 fall 5
         {% endfor %}

        listen keystone-public
          bind {{ auth_public_host }}:{{ openstack_keystone.port.public_ha }}
          balance roundrobin
          option  tcpka
          option  httpchk
          option  httplog
         {% for host in ansible_play_batch %}
         server node-{{ loop.index }} {{ host }}:{{ openstack_keystone.port.public }} check inter 2000 rise 2 fall 5
         {% endfor %}
  delegate_to: "{{ outer_item }}"
  tags:
    - keystone_ha

- name: Restart haproxy
  service:
    name: haproxy
    state: restarted
  delegate_to: "{{ outer_item }}"
  tags:
    - keystone_ha
