---
# roles/keystone/tasks/init_fernet.yml

- name: Initialize Fernet key repositories
  shell: "{{ item }}"
  with_items:
    - "keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone"
    - "keystone-manage credential_setup --keystone-user keystone --keystone-group keystone"
