---
- block:
  - name: Create the {{ user_name }} user
    os_user:
      name: "{{ user_name }}"
      password: "{{ user_password }}"
      domain: default
      default_project: service
      state: present
    run_once: true

  - name: Add the admin role to the {{ user_name }} user and service project
    os_user_role:
      user: "{{ user_name }}"
      role: admin
      project: service
    run_once: true

  - name: Create the {{ user_name }} service entity
    os_keystone_service:
      name: "{{ user_name }}"
      service_type: "{{ service_type }}"
      description: "{{ service_description }}"
      state: present
    run_once: true

  - name: Create the {{ service_type | capitalize }} service API endpoints
    os_keystone_endpoint:
      service: "{{ user_name }}"
      endpoint_interface: "{{ item }}"
      url: "http://{{ service_host }}:{{ service_port }}{{ service_api_version|default('') }}"
      region: RegionOne
      state: present
    loop:
      - admin
      - public
      - internal
    run_once: true

  environment:
    OS_PROJECT_DOMAIN_NAME: Default
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_NAME: admin
    OS_USERNAME: admin
    OS_PASSWORD: "{{ openstack_keystone.auth.password }}"
    OS_AUTH_URL: "http://{{ auth_admin_host }}:{{ auth_admin_port }}/v3"
    OS_IDENTITY_API_VERSION: 3
    OS_IMAGE_API_VERSION: 2
