---
- hosts: ceph_mon_host
  gather_facts: false
  tasks:
    - name: Install rsync
      yum:
        name: rsync
        state: present

    - name: Create a ceph resource pool
      shell: "{{ item }}"
      loop:
        - 'ceph osd pool create images 128 128'
        - 'ceph osd pool create volumes 128 128'
        - 'ceph osd pool create vms 128 128'
        - 'ceph osd pool create backups 128 128'

    - name: Create ceph storage key
      shell: "{{ item }}"
      loop:
        - "ceph auth get-or-create client.glance mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=images'"
        - "ceph auth get-or-create client.cinder mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=volumes, allow rwx pool=vms, allow rwx pool=images'"
        - "ceph auth get-or-create client.cinder-backup mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=backups'"
        - "ceph auth get-or-create client.glance -o /etc/ceph/ceph.client.glance.keyring"
        - "ceph auth get-or-create client.cinder -o /etc/ceph/ceph.client.cinder.keyring"
        - "ceph auth get-key client.cinder -o /etc/ceph/client.cinder.key"
        - "ceph auth get-or-create client.cinder-backup -o /etc/ceph/ceph.client.cinder-backup.keyring"

    - name: Pull ceph related key
      synchronize:
        mode: pull
        src: "{{ item }}"
        dest: "{{ inventory_dir }}/tmp/"
        archive: true
        checksum: true
      loop:
        - /etc/ceph/ceph.client.glance.keyring
        - /etc/ceph/ceph.client.cinder.keyring
        - /etc/ceph/client.cinder.key
        - /etc/ceph/ceph.client.cinder-backup.keyring
        - /etc/ceph/ceph.client.admin.keyring
        - /etc/ceph/ceph.conf

    - name: Delete section osd in {{ inventory_dir }}/tmp/ceph.conf
      ini_file:
        path: "{{ inventory_dir }}/tmp/ceph.conf"
        section: osd
        state: absent
      delegate_to: 127.0.0.1
