---
- name: Config memcached iptables
  iptables:
    action: insert
    chain: INPUT
    jump: ACCEPT
    source: "{{ network_openstack.management.cidr }}"
    protocol: tcp
    match: multiport
    destination_port: "{{ memcached.port}}"

- name: Insert tcp rule to /etc/sysconfig/iptables
  blockinfile:
    path: /etc/sysconfig/iptables
    marker: "# {mark} iptables rules for memcached {mark}"
    insertafter: '^:OUTPUT ACCEPT '
    block: |
      -A INPUT -s {{ network_openstack.management.cidr }} -p tcp -m multiport --dport {{ memcached.port }} -j ACCEPT
